### ISSUE TITLE
Traducción al portugués - Desaparición en el bosque.

### ISSUE THREAD

**Issue by vidimus** [ZombieJuanma/EscenariosMoM#1]
@ZombieJuanma ,  me pongo en contacto contigo porque un usuario brasileño de Valkyrie quiere traducir tu escenario de "Desparición en el bosque" al portugués, y obviamente necesita tu permiso y que luego actualices tu escenario con la traducción. Esto segundo, si no sabes hacerlo, yo podría hacerlo o explicártelo, no es complicado de todos modos.

En fin, que espero que leas esto pronto y me respondas. Lo cierto es que me parece una grandísima noticia que alguien quiera traducir tu escenario a otro idioma.

Me quedo a la espera de noticias tuyas.

**Comment by ZombieJuanma** [comment]
Hola, buenas @vidimus . Por mí no hay problema, lo único es que hace tiempo que no uso el Valkyrie y esta aplicación por lo que sí que necesitaría que me refresques un poco la memoria. Creo recordar que no era muy complicado pero si me lo explicas de nuevas mejor que mejor y ya lo hago yo o tú, no me importa ;)

**Comment by vidimus** [comment]
@ZombieJuanma , tranquilo, ya te pasaré el archivo para que sólo tengas que subirlo.
